### PR TITLE
A maven build for consideration. Also fixed some testing issues where failing tests went unnoticed.

### PR DESCRIPTION
**Pull request by ZhengXinCN**
Note: 
- A dedicated log4j configuration is used for the integration tests in order to remain below the 4MB test limit.
- Does not yet support to build a release.
- There execptions on the console during the build are due to https://github.com/eclipse/vert.x/issues/1625

### CODE REVIEW

**Comment by ZhengXinCN** [comment]
will fix the build

**Comment by mcweba** [comment]
Whoever reviews this changes, please wait with merging into master. I'm currently working on #174 which requires a release in the next few days.

**Comment by lbovet** [comment]
There are too many commits with same message. Could you squash them, please?

**Comment by ZhengXinCN** [comment]
Ok, I will create another PR.

**Pull request closed without merging**
